language: python
python:
    - "3.5"
    - "3.6"

# command to install dependencies
install:
    - pip install pipenv
    - pipenv install

# command to run tests and lint
script:
    - python -m unittest discover
    - pipenv check --style ./algviz
